<a href="https://colab.research.google.com/github/FernandaMalta/numpy-learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


**The Basics**

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1.0, 5.0, 3.0],[6.0, 7.0, 8.0]])
print(b)

[[1. 5. 3.]
 [6. 7. 8.]]


In [ ]:
# Get Dimension A
a.ndim

1

In [ ]:
#Get Shape
a.shape

(3,)

In [ ]:
# Get Type
a.dtype

dtype('int64')

In [ ]:
#Get Size
a.itemsize

8

In [ ]:
#Get Total size
a.nbytes

24

**Accessing/Changing Specifics elements, rows, columns, etc**

---



In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a Specific Element [r, c]
a[1,5]

13

In [ ]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [ ]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
a[1,5] = 20
print(a)

a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


*3-d example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get specific element (work outside in)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


**Initializing Different Types of Arrays**

---



In [ ]:
#All 0s Matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#All 1s matrix
np.ones((4,2,2), dtype= 'int')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [ ]:
#Any other number
np.full((2,2),99, dtype='float')

array([[99., 99.],
       [99., 99.]])

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#Random Decimal numbers
np.random.rand(4,2,3)

array([[[0.50672007, 0.57705192, 0.47136496],
        [0.22799027, 0.417096  , 0.80506562]],

       [[0.08998802, 0.67595358, 0.42976643],
        [0.04039056, 0.63753285, 0.05040434]],

       [[0.79059046, 0.15317501, 0.56310245],
        [0.34238445, 0.21712088, 0.95979386]],

       [[0.22997192, 0.09891755, 0.19927198],
        [0.15525021, 0.19859454, 0.81500982]]])

In [ ]:
#Another random decimal sample
np.random.random_sample(a.shape)

array([[0.90002789, 0.62232796, 0.77846672, 0.21228644, 0.81903694,
        0.42325848, 0.82300944],
       [0.18831832, 0.11958998, 0.62862563, 0.22968039, 0.08586172,
        0.84098372, 0.20942093]])

In [ ]:
#Random integer values
np.random.randint(7, size=(3,3))

array([[3, 4, 0],
       [1, 1, 1],
       [3, 2, 3]])

In [ ]:
#The indentity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


**Initialize Array Problem**

---



In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
out = np.zeros((7,7))

z = np.ones((5,5))
z[2,2] = 5
out[1:-1,1:-1] = z
print(out)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
