<a href="https://colab.research.google.com/github/FernandaMalta/numpy-learning/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


**The Basics**

---



In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1.0, 5.0, 3.0],[6.0, 7.0, 8.0]])
print(b)

[[1. 5. 3.]
 [6. 7. 8.]]


In [ ]:
# Get Dimension A
a.ndim

1

In [ ]:
#Get Shape
a.shape

(3,)

In [ ]:
# Get Type
a.dtype

dtype('int64')

In [ ]:
#Get Size
a.itemsize

8

In [ ]:
#Get Total size
a.nbytes

24

**Accessing/Changing Specifics elements, rows, columns, etc**

---



In [ ]:
import numpy as np

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a Specific Element [r, c]
a[1,5]

13

In [ ]:
#Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [ ]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [ ]:
a[1,5] = 20
print(a)

a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


*3-d example

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get specific element (work outside in)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


**Initializing Different Types of Arrays**

---



In [ ]:
#All 0s Matrix
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
#All 1s matrix
np.ones((4,2,2), dtype= 'int')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [ ]:
#Any other number
np.full((2,2),99, dtype='float')

array([[99., 99.],
       [99., 99.]])

In [ ]:
# Any other number (full_like)
np.full_like(a, 4)


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
#Random Decimal numbers
np.random.rand(4,2,3)

array([[[0.50672007, 0.57705192, 0.47136496],
        [0.22799027, 0.417096  , 0.80506562]],

       [[0.08998802, 0.67595358, 0.42976643],
        [0.04039056, 0.63753285, 0.05040434]],

       [[0.79059046, 0.15317501, 0.56310245],
        [0.34238445, 0.21712088, 0.95979386]],

       [[0.22997192, 0.09891755, 0.19927198],
        [0.15525021, 0.19859454, 0.81500982]]])

In [ ]:
#Another random decimal sample
np.random.random_sample(a.shape)

array([[0.90002789, 0.62232796, 0.77846672, 0.21228644, 0.81903694,
        0.42325848, 0.82300944],
       [0.18831832, 0.11958998, 0.62862563, 0.22968039, 0.08586172,
        0.84098372, 0.20942093]])

In [ ]:
#Random integer values
np.random.randint(7, size=(3,3))

array([[3, 4, 0],
       [1, 1, 1],
       [3, 2, 3]])

In [ ]:
#The indentity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(np.full_like(a, 100))

[[100 100 100 100 100]
 [100 100 100 100 100]]


**Initialize Array Problem**

---



In [ ]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:4,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
out = np.zeros((7,7))

z = np.ones((5,5))
z[2,2] = 5
out[1:-1,1:-1] = z
print(out)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 5. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


**Mathematics**

---



In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a -2 

array([-1,  0,  1,  2])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b = np.array([1,5,9,8])
print(b)

[1 5 9 8]


In [ ]:
a + b

array([ 2,  7, 12, 12])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
#Take the sin (for cos, just do the opposite)
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

---



In [4]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [5]:
#Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

**Statistics**


---



In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
stats

In [ ]:
np.min(stats, axis=1)

In [ ]:
np.sum(stats)

In [ ]:
np.max(stats)


In [ ]:
#Question:

a = np.array(([1,2,3,4,5], [6,7,8,9,10]))
b = np.max(a, axis=1).sum()
print(b)

**Reorganizing Arrays**


---



In [ ]:
bef = np.array(([1,2,3,4], [5,6,7,8]))
print(bef)

af = bef.reshape((4,2))
print(af)

In [ ]:
#Vertically stacking vectors
vr1 = np.array([1,2,3,4])
vr2 = np.array([5,6,7,8])

np.vstack((vr1,vr2))

In [6]:
#Horizontally stacking vectors
ho1 = np.ones((2,4))
ho2 = np.ones((2,2))

np.hstack((ho1,ho2))



array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

**Load Data from file**


In [22]:
from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))



Saving data.txt to data (3).txt
User uploaded file "data.txt" with length 73 bytes


In [27]:
filedata = np.genfromtxt('data (3).txt', delimiter=',')
filedata.astype('int')
filedata = filedata.astype('int')
filedata

array([[ 1,  2,  3,  4,  5,  6,  7, 11, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 23, 50],
       [15, 16, 17, 18, 19, 20, 21, 22, 33]])

**Boolean Masking and Advanced Indexing**


---



In [28]:
filedata > 50

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False]])

In [30]:
filedata[filedata > 30]

array([50, 33])

In [31]:
#You can index with a list in NumPy
a = np.array([1,2,3,4,5])
a[[1,3]]

array([2, 4])

In [40]:
np.all(filedata > 8, axis=0)

array([False, False, False, False, False, False, False,  True,  True])

In [42]:
filedata[1:2, 0:2]

array([[8, 9]])